# Generated by Django 5.2.7 on 2025-10-10 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='owner',
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this newsletter.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='The display name of the newsletter.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional description of this newsletter.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the newsletter was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the newsletter was last updated.')),
                ('owner', models.ForeignKey(help_text='The account that owns this newsletter.', on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='newsletter',
            field=models.ForeignKey(help_text='The newsletter this subscriber belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='subscriber.newsletter'),
        ),
    ]
