# Generated by Django 5.2.7 on 2025-10-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_remove_subscriber_owner_newsletter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='description',
        ),
    ]
