# Generated by Django 5.2.7 on 2025-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_remove_newsletter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('newsletter', 'email'), name='unique_subscriber_per_newsletter'),
        ),
    ]
